# Generated by Django 5.2.17 on 2026-09-16 09:17

import django.core.validators
import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('type', models.CharField(choices=[('single', 'Один верный ответ'), ('multiple', 'Несколько верных ответов')], default='single', help_text='multiple ставится, когда верных вариантов больше одного.', max_length=10, verbose_name='тип')),
                ('position', models.PositiveSmallIntegerField(verbose_name='номер в тесте')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='верный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'вариант ответа',
                'verbose_name_plural': 'варианты ответа',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='время на тест, мин')),
                ('questions_file', models.FileField(blank=True, help_text='Исходный JSON остаётся здесь как архив загрузки.', upload_to='tests/questions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['json'])], verbose_name='файл с вопросами')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать на сайте')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='catalog.module', verbose_name='блок')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.test', verbose_name='тест'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('module', 'title'), name='test_title_unique_per_module'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1), ('duration_minutes__lte', 180)), name='test_duration_minutes_in_range'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('test', 'position'), name='question_position_unique_per_test'),
        ),
    ]
