# Generated by Django 5.2.17 on 2026-09-16 09:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('bg_color', models.CharField(default='#C9E9F6', help_text='Фон карточки в формате #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Цвет задаётся в формате #RRGGBB, например #C9E9F6.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='цвет карточки')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='стикер')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать на сайте')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('bg_color__regex', '^#[0-9A-Fa-f]{6}$')), name='category_bg_color_is_hex')],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать на сайте')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'блок',
                'verbose_name_plural': 'блоки',
                'ordering': ('title',),
                'constraints': [models.UniqueConstraint(fields=('category', 'title'), name='module_title_unique_per_category')],
            },
        ),
    ]
